name: exemplo_cubit
description: "Aplicação de exemplo para o uso do Cubit."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.3
  flutter_bloc: ^8.1.4


  google_fonts: 6.1.0
  meta: ^1.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
